### ISSUE TITLE
How I can execute it in android?

### ISSUE THREAD

**Issue by luisgzafra** [programa-stic/snapchat-decrypt#6]
Hello, how I can execute the script in Android 4?

This is not an issue, but I don't know where I can post it :)

Thanks!

**Comment by zerokes** [comment]
Hi Luis, the script is ment to be executed in a PC connected to the device. Bare in mind that you must have a rooted device running adb as root (try ADBD ROOT app) and that the script only obtains unseen snapchats. You simply download the script and run it on your PC with python.
